---
- name: Optional - Bitwarden Server URL konfigurieren
  ansible.builtin.command: "bw config server {{ bw_server_url }}"
  changed_when: false
  when: bw_server_url is defined and bw_server_url != ""

- name: Headless Login via API Keys
  ansible.builtin.command: bw login --apikey
  environment:
    BW_CLIENTID: "{{ bw_client_id }}"
    BW_CLIENTSECRET: "{{ bw_client_secret }}"
  register: bw_login
  changed_when: false
  failed_when: 
    - bw_login.rc != 0 
    - "'already logged in' not in bw_login.stderr and 'already logged in' not in bw_login.stdout"

- name: Vault entsperren und Session-ID generieren
  ansible.builtin.command: bw unlock --passwordenv BW_PASSWORD --raw
  environment:
    BW_PASSWORD: "{{ bw_master_password }}"
  register: bw_unlock
  no_log: true
  changed_when: false

- name: Session-ID als Fact global verfügbar machen
  ansible.builtin.set_fact:
    bw_session: "{{ bw_unlock.stdout }}"
  no_log: true