---
- name: Optional - Bitwarden Server URL konfigurieren
  ansible.builtin.command: "bw config server {{ bitwarden_auth_server_url }}"
  changed_when: false
  when: bitwarden_auth_server_url is defined and bitwarden_auth_server_url != ""

- name: Stelle sicher, dass der Vault vor dem Login gesperrt ist
  ansible.builtin.command: bw lock
  failed_when: false
  changed_when: false

- name: Headless Login via API Keys
  ansible.builtin.command: bw login --apikey
  environment:
    BW_CLIENTID: "{{ bitwarden_auth_client_id }}"
    BW_CLIENTSECRET: "{{ bitwarden_auth_client_secret }}"
  register: bitwarden_auth_login
  changed_when: false
  failed_when:
    - bitwarden_auth_login.rc != 0
    - "'already logged in' not in bitwarden_auth_login.stderr and 'already logged in' not in bitwarden_auth_login.stdout"

- name: Vault entsperren und Session-ID generieren
  ansible.builtin.command: bw unlock --passwordenv BW_PASSWORD --raw
  environment:
    BW_PASSWORD: "{{ bitwarden_auth_master_password }}"
  register: bitwarden_auth_unlock
  no_log: true
  changed_when: false

- name: Session-ID als Fact global verfügbar machen
  ansible.builtin.set_fact:
    bitwarden_auth_session: "{{ bitwarden_auth_unlock.stdout }}"
  no_log: true
