namespace: rds
name: rds_bitwarden
version: 1.0.7
readme: README.md
authors:
  - Björn Hinz <bjoern.hinz@rohwerder.net>
description: "Bitwarden Automatisierung für CI/CD"
dependencies:
  "community.general": ">=6.0.0"
