namespace: bhinz
name: rds_bitwarden
version: 1.0.10
readme: README.md
authors:
  - Björn Hinz <bjoern@hinz.tv>
description: "Bitwarden automation for CI/CD"
repository: https://github.com/bhinz/rds_bitwarden
license:
  - MIT
dependencies: {}
