---
# Diese Variablen müssen von außen (z.B. Semaphore) übergeben werden:
# bitwarden_auth_client_id: ""
# bitwarden_auth_client_secret: ""
# bitwarden_auth_master_password: ""

# Optional für selbstgehostete Instanzen:
# bitwarden_auth_server_url: ""
