---
# These variables must be provided externally:
# bitwarden_auth_client_id: ""
# bitwarden_auth_client_secret: ""
# bitwarden_auth_master_password: ""

# Optional for self-hosted instances:
# bitwarden_auth_server_url: ""
